cmake_minimum_required(VERSION 3.21)
project(xlate C CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(LLVM CONFIG REQUIRED)

set(RELLUME_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../deps/rellume)
add_executable(xlate src/xlate.cpp src/macho.cpp src/objc.cpp)
target_include_directories(xlate PRIVATE ${LLVM_INCLUDE_DIRS} ${RELLUME_DIR}/include ${RELLUME_DIR}/build/data/rellume)
target_link_libraries(xlate PRIVATE LLVM ${RELLUME_DIR}/build/src/librellume.dylib)
set_target_properties(xlate PROPERTIES BUILD_RPATH ${RELLUME_DIR}/build/src)
find_package(Clang CONFIG REQUIRED)
add_executable(xlgen src/xlgen.cpp)
target_link_libraries(xlgen PRIVATE clang-cpp LLVM)
target_include_directories(xlgen PRIVATE ${LLVM_INCLUDE_DIRS} ${CLANG_INCLUDE_DIRS})
